spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.profiles.active=dev

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.issuer=${APP_URL:http://localhost:8080}