# Database credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}

# JWT secret key
jwt.secret-key=${JWT_SECRET_KEY}

# Spring mail credentials
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# AWS S3 Access
aws.bucket.name=${S3_BUCKET_NAME}
aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_KEY}