spring.application.name=backend

# Database config
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Environment config
spring.profiles.active=prod

# Context path
server.servlet.context-path=/api/v1

# Swagger docs config
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/docs

# Env vars
jwt.issuer=${APP_URL:http://localhost:8080}

# Frontend url
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# File size limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) [%clr(%X{requestId:-NO-ID}){cyan}] %clr(%logger{36}){magenta} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{requestId:-NO-REQUEST-ID}] %logger{36} - %msg%n
logging.file.name=logs/app.log